---
apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    name: voting-app-server
    author: intelliqit
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-app

