---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
   name: worker-app
   author: intelliqit
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: woker-app
        author: intelliqit
    spec:
      containers:
        - name: my-worker
          image: dockersamples/examplevotingapp_worker
...